#workspace.resolver = "2"
[workspace]
resolver = "2"
members = [
    "shire",
    "shire-core",
    "shire-cli",
    "shire-wasm",
    "shire",

    # languages
    "language/shire-lang-core",
    "language/shire-java",
]
