[package]
name = "shire-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7"

# This library provides a streaming parser for locating URLs.
urlocator = "0.1.4"
regex = "1.10.6"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
path = "src/lib.rs"